### ISSUE TITLE
Contact for help

### ISSUE THREAD

**Issue by Hamza-101** [marek-robak/Drone-2d-custom-gym-env-for-reinforcement-learning#1]
Hello Marak, I came across this project and wanted some advice, for a project that is similar to this. I had no other way of contacting and wanted to ask if you could give me a few pointers?
Regards,
Hamza

**Comment by marek-robak** [comment]
Hi, of course, I wrote to you on LinkedIn

**Comment by Hamza-101** [comment]
Thank you.
